# Generated by Django 3.1.4 on 2020-12-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name_plural': 'Content'},
        ),
        migrations.AddField(
            model_name='content',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='content',
            name='categories',
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(related_name='content_categories', to='api.Category'),
        ),
    ]
